### ISSUE TITLE
Cursor position in text editors

### ISSUE THREAD

**Issue by asheroto** [PowerShell/openssh-portable#490]
Hello,

Using OpenSSH for Windows, if I remote into a server and try to edit a test file such as by typing

`nano readme.txt`

I can edit it fine, but the cursor position is not visible when I move with the arrow keys.

The same command using Windows PowerShell works fine, showing the cursor position.

**Comment by bagajjal** [comment]
Closing the issue here.. please open a new issue at https://github.com/PowerShell/Win32-OpenSSH/issues.

Please provide the below required information in the new issue.

What are client, server operating systems?
What version of OpenSSH are you using?
> The same command using Windows PowerShell works fine, showing the cursor position.

Are you saying, if you try openssh ssh.exe from windows powershell then you are seeing the cursor?
